# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-05 07:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='KentUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purchase_date', models.DateField()),
                ('kro_number', models.CharField(max_length=31)),
                ('name', models.CharField(max_length=63)),
                ('address', models.TextField()),
                ('landmark', models.TextField()),
                ('mobile_number', models.CharField(max_length=511)),
                ('last_amc_date', models.DateField()),
                ('warranty_status', models.CharField(choices=[(b'warranty', b'warranty'), (b'warranty_expired', b'warranty_expired'), (b'amc 4500', b'amc 4500'), (b'amc 1000', b'amc 1000'), (b'amc 750', b'amc 750')], max_length=63)),
                ('accessories', models.CharField(max_length=127)),
                ('remark', models.CharField(max_length=127)),
            ],
        ),
    ]
