# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-05 07:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messy', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kentuser',
            name='accessories',
            field=models.CharField(blank=True, max_length=127, null=True),
        ),
        migrations.AlterField(
            model_name='kentuser',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='kentuser',
            name='kro_number',
            field=models.CharField(blank=True, max_length=31, null=True),
        ),
        migrations.AlterField(
            model_name='kentuser',
            name='landmark',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='kentuser',
            name='last_amc_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='kentuser',
            name='mobile_number',
            field=models.CharField(blank=True, max_length=511, null=True),
        ),
        migrations.AlterField(
            model_name='kentuser',
            name='remark',
            field=models.CharField(blank=True, max_length=127, null=True),
        ),
        migrations.AlterField(
            model_name='kentuser',
            name='warranty_status',
            field=models.CharField(blank=True, choices=[(b'warranty', b'warranty'), (b'warranty_expired', b'warranty_expired'), (b'amc 4500', b'amc 4500'), (b'amc 1000', b'amc 1000'), (b'amc 750', b'amc 750')], max_length=63, null=True),
        ),
    ]
