# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-06-05 09:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messy', '0002_auto_20170605_0727'),
    ]

    operations = [
        migrations.AddField(
            model_name='kentuser',
            name='month',
            field=models.CharField(blank=True, max_length=31, null=True),
        ),
        migrations.AlterField(
            model_name='kentuser',
            name='purchase_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
