# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-05 10:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('messy', '0003_auto_20170605_0908'),
    ]

    operations = [
        migrations.RenameField(
            model_name='kentuser',
            old_name='mobile_number',
            new_name='phone',
        ),
    ]
