# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-06 05:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('messy', '0004_auto_20170605_1021'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceTask',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_and_time', models.DateTimeField()),
                ('status', models.BooleanField(default=False)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='messy.KentUser')),
            ],
        ),
        migrations.CreateModel(
            name='Technician',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=63)),
                ('phone', models.CharField(max_length=127)),
                ('address', models.CharField(max_length=511)),
            ],
        ),
        migrations.AddField(
            model_name='servicetask',
            name='technician',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='messy.Technician'),
        ),
    ]
