# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-06 05:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('messy', '0005_auto_20170606_0523'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=63)),
                ('phone', models.CharField(max_length=127)),
                ('address', models.CharField(max_length=511)),
                ('date_of_joining', models.DateField()),
            ],
        ),
        migrations.RemoveField(
            model_name='technician',
            name='address',
        ),
        migrations.RemoveField(
            model_name='technician',
            name='name',
        ),
        migrations.RemoveField(
            model_name='technician',
            name='phone',
        ),
        migrations.AddField(
            model_name='servicetask',
            name='technician_departed',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='servicetask',
            name='technician_reached',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='technician',
            name='employee',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='messy.Employee'),
        ),
    ]
