# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-06 06:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('messy', '0006_auto_20170606_0557'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicetask',
            name='date_and_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='servicetask',
            name='technician',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='messy.Technician'),
        ),
        migrations.AlterField(
            model_name='servicetask',
            name='technician_departed',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='servicetask',
            name='technician_reached',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
