# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-06 06:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messy', '0007_auto_20170606_0602'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeAttendance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('employees', models.ManyToManyField(to='messy.Employee')),
            ],
        ),
    ]
