# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-06 09:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messy', '0010_auto_20170606_0919'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='pic',
            field=models.FileField(default=1, upload_to=b'static/profile/'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='photo',
            name='url',
            field=models.URLField(max_length=2047, null=True),
        ),
    ]
