# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-09 04:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messy', '0011_auto_20170606_0924'),
    ]

    operations = [
        migrations.AddField(
            model_name='kentuser',
            name='area',
            field=models.CharField(blank=True, max_length=127, null=True),
        ),
        migrations.AddField(
            model_name='kentuser',
            name='sub_area',
            field=models.CharField(blank=True, max_length=127, null=True),
        ),
        migrations.AlterField(
            model_name='photo',
            name='url',
            field=models.URLField(blank=True, max_length=2047, null=True),
        ),
    ]
