# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-13 04:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messy', '0012_auto_20170609_0453'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kentuser',
            name='area',
            field=models.CharField(blank=True, max_length=1027, null=True),
        ),
        migrations.AlterField(
            model_name='kentuser',
            name='sub_area',
            field=models.CharField(blank=True, max_length=1027, null=True),
        ),
    ]
